# Generated by Django 5.0.9 on 2026-09-10 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('medication_stop_start', 'Medication stop/start'), ('severe_interaction', 'Severe drug interaction'), ('emergency_sign', 'Emergency / red-flag symptom')], max_length=32)),
                ('matched_terms', models.JSONField(blank=True, default=list)),
                ('trigger_text', models.TextField(help_text='The user/model text snippet that triggered this event.')),
                ('response_shown', models.TextField(help_text='The exact redirect text shown to the user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit_recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visits.visitrecording')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='safety_esca_categor_dd221d_idx'), models.Index(fields=['user'], name='safety_esca_user_id_4e4e1e_idx')],
            },
        ),
    ]
