# Generated by Django 5.0.9 on 2026-09-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreachIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovered_at', models.DateTimeField()),
                ('affected_user_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('ftc_notified_at', models.DateTimeField(blank=True, null=True)),
                ('users_notified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('privacy_policy', 'Privacy policy'), ('breach_notice_plan', 'Breach notice plan')], max_length=32)),
                ('version_label', models.CharField(max_length=20)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('document_url', models.URLField(blank=True)),
            ],
        ),
    ]
