# Generated by Django 5.0.9 on 2026-09-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Set from the first question so the history list reads like a list of topics.",
                max_length=120,
            ),
        ),
    ]
