# Generated by Django 5.0.9 on 2026-09-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatsession_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="follow_ups",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Aira's suggested next questions (assistant messages only), shown as tappable chips.",
            ),
        ),
    ]
