# Generated by Django 5.0.9 on 2026-09-10 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('lab_result', 'Lab result'), ('discharge_summary', 'Discharge summary'), ('prescription', 'Prescription'), ('imaging', 'Imaging'), ('other', 'Other')], default='other', max_length=32)),
                ('source_institution', models.CharField(blank=True, help_text='Freeform — which hospital/portal this came from, if known. Powers the cross-institution timeline.', max_length=255)),
                ('extracted_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
