# Generated by Django 5.0.9 on 2026-09-24 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatmessage_follow_ups"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="chat_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when the file was shared in an Ask Aira conversation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attachments",
                to="chat.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="file_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="original_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="size_bytes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
